#!/bin/sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/common.sh" ]; then
    . "$SCRIPT_DIR/common.sh"
fi

CONF_FILE="/etc/sysctl.d/99-easy42.conf"

echo "=== Configuring sysctl parameters ==="

$SUDO mkdir -p /etc/sysctl.d

cat << 'EOF' | $SUDO tee "$CONF_FILE" >/dev/null
# Generated by easy42 Device Helper
net.ipv4.ip_forward=1
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.default.rp_filter=0
net.ipv6.conf.all.forwarding=1
net.ipv6.conf.default.forwarding=1
EOF

$SUDO chmod 644 "$CONF_FILE"

# Apply parameters immediately
if command -v sysctl >/dev/null 2>&1; then
    $SUDO sysctl -p "$CONF_FILE" >/dev/null 2>&1 || true
    $SUDO sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true
    $SUDO sysctl -w net.ipv4.conf.all.rp_filter=0 >/dev/null 2>&1 || true
    $SUDO sysctl -w net.ipv4.conf.default.rp_filter=0 >/dev/null 2>&1 || true
    $SUDO sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null 2>&1 || true
    $SUDO sysctl -w net.ipv6.conf.default.forwarding=1 >/dev/null 2>&1 || true
fi

echo "Sysctl parameters successfully written to $CONF_FILE and applied"
exit 0
