package compiler

import (
	"testing"
)

func TestExtractWgMTU(t *testing.T) {
	conf := `
[Interface]
Address = 10.0.0.1/30
MTU = 1380
PrivateKey = ABC=

[Peer]
PublicKey = DEF=
`
	mtu := ExtractWgMTU(conf)
	if mtu != 1380 {
		t.Fatalf("Expected MTU 1380, got %d", mtu)
	}

	confNoMTU := `
[Interface]
Address = 10.0.0.1/30
`
	if ExtractWgMTU(confNoMTU) != 0 {
		t.Fatalf("Expected MTU 0 when missing, got %d", ExtractWgMTU(confNoMTU))
	}
}

func TestRequiresWgRestart(t *testing.T) {
	baseConf := `
# Auto-generated by easy42. Do not edit manually.
[Interface]
Address = fe80::1/64
ListenPort = 51820
PrivateKey = AAA=
MTU = 1420
PostUp = sysctl -w net.ipv4.conf.%i.rp_filter=0
Table = off

[Peer]
PublicKey = BBB=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 1.2.3.4:51820
`

	// 1. Peer endpoint change -> does NOT require restart
	endpointChanged := `
# Auto-generated by easy42. Do not edit manually.
[Interface]
Address = fe80::1/64
ListenPort = 51820
PrivateKey = AAA=
MTU = 1420
PostUp = sysctl -w net.ipv4.conf.%i.rp_filter=0
Table = off

[Peer]
PublicKey = BBB=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 5.6.7.8:51820
`
	if RequiresWgRestart(baseConf, endpointChanged) {
		t.Errorf("Expected endpoint change NOT to require restart")
	}

	// 2. MTU change -> DOES require restart
	mtuChanged := `
# Auto-generated by easy42. Do not edit manually.
[Interface]
Address = fe80::1/64
ListenPort = 51820
PrivateKey = AAA=
MTU = 1380
PostUp = sysctl -w net.ipv4.conf.%i.rp_filter=0
Table = off

[Peer]
PublicKey = BBB=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 1.2.3.4:51820
`
	if !RequiresWgRestart(baseConf, mtuChanged) {
		t.Errorf("Expected MTU change to require restart")
	}

	// 3. Address change -> DOES require restart
	addressChanged := `
# Auto-generated by easy42. Do not edit manually.
[Interface]
Address = fe80::2/64
ListenPort = 51820
PrivateKey = AAA=
MTU = 1420
PostUp = sysctl -w net.ipv4.conf.%i.rp_filter=0
Table = off

[Peer]
PublicKey = BBB=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 1.2.3.4:51820
`
	if !RequiresWgRestart(baseConf, addressChanged) {
		t.Errorf("Expected Address change to require restart")
	}

	// 4. Hook change -> DOES require restart
	hookChanged := `
# Auto-generated by easy42. Do not edit manually.
[Interface]
Address = fe80::1/64
ListenPort = 51820
PrivateKey = AAA=
MTU = 1420
PostUp = sysctl -w net.ipv4.conf.%i.rp_filter=0
PostUp = ip rule add ...
Table = off

[Peer]
PublicKey = BBB=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 1.2.3.4:51820
`
	if !RequiresWgRestart(baseConf, hookChanged) {
		t.Errorf("Expected PostUp change to require restart")
	}

	// 5. Empty current content -> DOES require restart
	if !RequiresWgRestart("", baseConf) {
		t.Errorf("Expected empty current content to require restart")
	}
}
