package compiler

import (
	"bytes"
	"fmt"
	"strings"

	"easy42/internal/config"
	"easy42/internal/crypto"
)

// GenerateWgConfigContent generates the standard WireGuard configuration content for a node's end of a link
func GenerateWgConfigContent(
	selfNode *config.Node,
	peerNode *config.Node,
	selfEnd *config.LinkEnd,
	peerEnd *config.LinkEnd,
	vault *crypto.KeyVault,
) (string, error) {
	var privateKey string
	if selfEnd.PrivateKey != "" {
		decrypted, err := vault.DecryptField(selfEnd.PrivateKey)
		if err != nil {
			return "", fmt.Errorf("failed to decrypt private key for node %s: %w", selfNode.Name, err)
		}
		privateKey = decrypted
	}

	address := selfEnd.Address
	if address == "" {
		derived, err := DeriveIPv6LinkLocal(selfNode.IP)
		if err != nil {
			return "", fmt.Errorf("failed to derive link-local address for node %s: %w", selfNode.Name, err)
		}
		address = derived
	}

	listenPort := selfEnd.ListenPort
	if listenPort == 0 && peerNode != nil {
		listenPort = DerivePortFromIP(peerNode.IP)
	}

	peerAddrOnly, err := DeriveIPv6LinkLocalAddressOnly(peerNode.IP)
	if err != nil {
		return "", fmt.Errorf("failed to derive peer link-local address for node %s: %w", peerNode.Name, err)
	}

	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by easy42. Do not edit manually.\n")
	buf.WriteString("[Interface]\n")
	buf.WriteString(fmt.Sprintf("Address = %s\n", address))
	if listenPort > 0 {
		buf.WriteString(fmt.Sprintf("ListenPort = %d\n", listenPort))
	}
	if privateKey != "" {
		buf.WriteString(fmt.Sprintf("PrivateKey = %s\n", privateKey))
	}
	mtu := selfEnd.MTU
	if mtu <= 0 {
		mtu = 1420
	}
	buf.WriteString(fmt.Sprintf("MTU = %d\n", mtu))
	buf.WriteString("Table = off\n\n")

	buf.WriteString("[Peer]\n")
	buf.WriteString(fmt.Sprintf("PublicKey = %s\n", peerEnd.PublicKey))
	buf.WriteString(fmt.Sprintf("AllowedIPs = %s/128, 0.0.0.0/0, ::/0\n", peerAddrOnly))

	// Resolve endpoint if selfEnd.Endpoint is set or derived
	endpoint := selfEnd.Endpoint
	if endpoint == "" {
		peerListenPort := 0
		if peerEnd != nil && peerEnd.ListenPort > 0 {
			peerListenPort = peerEnd.ListenPort
		} else if selfNode != nil {
			peerListenPort = DerivePortFromIP(selfNode.IP)
		}
		derivedEP, _ := ResolvePeerEndpoint(selfNode, peerNode, nil, peerListenPort)
		endpoint = derivedEP
	}

	if endpoint != "" {
		buf.WriteString(fmt.Sprintf("Endpoint = %s\n", endpoint))
	}

	keepalive := selfEnd.PersistentKeepalive
	if keepalive == 0 && endpoint != "" {
		keepalive = 25
	}
	if keepalive > 0 {
		buf.WriteString(fmt.Sprintf("PersistentKeepalive = %d\n", keepalive))
	}

	return buf.String(), nil
}

// GetInterfaceName returns the standard wg42<peer_name> interface name
func GetInterfaceName(peerName string) string {
	cleanName := strings.TrimSpace(peerName)
	if len(cleanName) > 11 {
		cleanName = cleanName[:11]
	}
	return fmt.Sprintf("wg42%s", cleanName)
}
