// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManageInterface_Action int32

const (
	ManageInterface_UP      ManageInterface_Action = 0
	ManageInterface_DOWN    ManageInterface_Action = 1
	ManageInterface_RESTART ManageInterface_Action = 2
	ManageInterface_SYNC_WG ManageInterface_Action = 3
	ManageInterface_DELETE  ManageInterface_Action = 4
)

// Enum value maps for ManageInterface_Action.
var (
	ManageInterface_Action_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "RESTART",
		3: "SYNC_WG",
		4: "DELETE",
	}
	ManageInterface_Action_value = map[string]int32{
		"UP":      0,
		"DOWN":    1,
		"RESTART": 2,
		"SYNC_WG": 3,
		"DELETE":  4,
	}
)

func (x ManageInterface_Action) Enum() *ManageInterface_Action {
	p := new(ManageInterface_Action)
	*p = x
	return p
}

func (x ManageInterface_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManageInterface_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (ManageInterface_Action) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x ManageInterface_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManageInterface_Action.Descriptor instead.
func (ManageInterface_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13, 0}
}

type LookingGlassCmd_Tool int32

const (
	LookingGlassCmd_PING       LookingGlassCmd_Tool = 0
	LookingGlassCmd_TRACEROUTE LookingGlassCmd_Tool = 1
	LookingGlassCmd_BIRDC      LookingGlassCmd_Tool = 2
	LookingGlassCmd_CUSTOM     LookingGlassCmd_Tool = 3
)

// Enum value maps for LookingGlassCmd_Tool.
var (
	LookingGlassCmd_Tool_name = map[int32]string{
		0: "PING",
		1: "TRACEROUTE",
		2: "BIRDC",
		3: "CUSTOM",
	}
	LookingGlassCmd_Tool_value = map[string]int32{
		"PING":       0,
		"TRACEROUTE": 1,
		"BIRDC":      2,
		"CUSTOM":     3,
	}
)

func (x LookingGlassCmd_Tool) Enum() *LookingGlassCmd_Tool {
	p := new(LookingGlassCmd_Tool)
	*p = x
	return p
}

func (x LookingGlassCmd_Tool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LookingGlassCmd_Tool) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[1].Descriptor()
}

func (LookingGlassCmd_Tool) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[1]
}

func (x LookingGlassCmd_Tool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LookingGlassCmd_Tool.Descriptor instead.
func (LookingGlassCmd_Tool) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16, 0}
}

// AgentMessage is the top-level envelope for all WebSocket messages.
type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Seq       uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_RegisterReq
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Telemetry
	//	*AgentMessage_CommandResp
	//	*AgentMessage_ProbeResp
	//	*AgentMessage_RegisterResp
	//	*AgentMessage_HeartbeatAck
	//	*AgentMessage_CommandReq
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AgentMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegisterReq() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RegisterReq); ok {
			return x.RegisterReq
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTelemetry() *TelemetryReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResp() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandResp); ok {
			return x.CommandResp
		}
	}
	return nil
}

func (x *AgentMessage) GetProbeResp() *ProbeResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ProbeResp); ok {
			return x.ProbeResp
		}
	}
	return nil
}

func (x *AgentMessage) GetRegisterResp() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RegisterResp); ok {
			return x.RegisterResp
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandReq() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandReq); ok {
			return x.CommandReq
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_RegisterReq struct {
	// Agent -> Server
	RegisterReq *RegisterRequest `protobuf:"bytes,10,opt,name=register_req,json=registerReq,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Telemetry struct {
	Telemetry *TelemetryReport `protobuf:"bytes,12,opt,name=telemetry,proto3,oneof"`
}

type AgentMessage_CommandResp struct {
	CommandResp *CommandResponse `protobuf:"bytes,13,opt,name=command_resp,json=commandResp,proto3,oneof"`
}

type AgentMessage_ProbeResp struct {
	ProbeResp *ProbeResponse `protobuf:"bytes,14,opt,name=probe_resp,json=probeResp,proto3,oneof"`
}

type AgentMessage_RegisterResp struct {
	// Server -> Agent
	RegisterResp *RegisterResponse `protobuf:"bytes,20,opt,name=register_resp,json=registerResp,proto3,oneof"`
}

type AgentMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,21,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type AgentMessage_CommandReq struct {
	CommandReq *CommandRequest `protobuf:"bytes,22,opt,name=command_req,json=commandReq,proto3,oneof"`
}

func (*AgentMessage_RegisterReq) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Telemetry) isAgentMessage_Payload() {}

func (*AgentMessage_CommandResp) isAgentMessage_Payload() {}

func (*AgentMessage_ProbeResp) isAgentMessage_Payload() {}

func (*AgentMessage_RegisterResp) isAgentMessage_Payload() {}

func (*AgentMessage_HeartbeatAck) isAgentMessage_Payload() {}

func (*AgentMessage_CommandReq) isAgentMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	OsInfo        string                 `protobuf:"bytes,3,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TelemetryIntervalSecs uint32                 `protobuf:"varint,3,opt,name=telemetry_interval_secs,json=telemetryIntervalSecs,proto3" json:"telemetry_interval_secs,omitempty"` // Reporting interval in seconds (e.g. 10)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterResponse) GetTelemetryIntervalSecs() uint32 {
	if x != nil {
		return x.TelemetryIntervalSecs
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type TelemetryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *SystemMetrics         `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Interfaces    []*InterfaceMetrics    `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	WgPeers       []*WgPeerMetrics       `protobuf:"bytes,3,rep,name=wg_peers,json=wgPeers,proto3" json:"wg_peers,omitempty"`
	BirdProtocols []*BirdProtocolStatus  `protobuf:"bytes,4,rep,name=bird_protocols,json=birdProtocols,proto3" json:"bird_protocols,omitempty"`
	Disks         []*DiskMetrics         `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryReport) Reset() {
	*x = TelemetryReport{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryReport) ProtoMessage() {}

func (x *TelemetryReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryReport.ProtoReflect.Descriptor instead.
func (*TelemetryReport) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryReport) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *TelemetryReport) GetInterfaces() []*InterfaceMetrics {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *TelemetryReport) GetWgPeers() []*WgPeerMetrics {
	if x != nil {
		return x.WgPeers
	}
	return nil
}

func (x *TelemetryReport) GetBirdProtocols() []*BirdProtocolStatus {
	if x != nil {
		return x.BirdProtocols
	}
	return nil
}

func (x *TelemetryReport) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DiskMetrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskMetrics) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetrics) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type SystemMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent       float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	UptimeSeconds    uint64                 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LoadAvg          []float32              `protobuf:"fixed32,5,rep,packed,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"` // [1m, 5m, 15m]
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SystemMetrics) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *SystemMetrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemMetrics) GetLoadAvg() []float32 {
	if x != nil {
		return x.LoadAvg
	}
	return nil
}

type InterfaceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsUp          bool                   `protobuf:"varint,2,opt,name=is_up,json=isUp,proto3" json:"is_up,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     uint64                 `protobuf:"varint,5,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     uint64                 `protobuf:"varint,6,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	RxErrors      uint64                 `protobuf:"varint,7,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors      uint64                 `protobuf:"varint,8,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	Addresses     []string               `protobuf:"bytes,9,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceMetrics) Reset() {
	*x = InterfaceMetrics{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceMetrics) ProtoMessage() {}

func (x *InterfaceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceMetrics.ProtoReflect.Descriptor instead.
func (*InterfaceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *InterfaceMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceMetrics) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *InterfaceMetrics) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceMetrics) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceMetrics) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *InterfaceMetrics) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *InterfaceMetrics) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *InterfaceMetrics) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *InterfaceMetrics) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type WgPeerMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName       string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PublicKey           string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint            string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LastHandshakeTime   int64                  `protobuf:"varint,4,opt,name=last_handshake_time,json=lastHandshakeTime,proto3" json:"last_handshake_time,omitempty"` // Unix epoch seconds
	RxBytes             uint64                 `protobuf:"varint,5,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes             uint64                 `protobuf:"varint,6,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	PersistentKeepalive int64                  `protobuf:"varint,7,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WgPeerMetrics) Reset() {
	*x = WgPeerMetrics{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WgPeerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WgPeerMetrics) ProtoMessage() {}

func (x *WgPeerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WgPeerMetrics.ProtoReflect.Descriptor instead.
func (*WgPeerMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *WgPeerMetrics) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *WgPeerMetrics) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WgPeerMetrics) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WgPeerMetrics) GetLastHandshakeTime() int64 {
	if x != nil {
		return x.LastHandshakeTime
	}
	return 0
}

func (x *WgPeerMetrics) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *WgPeerMetrics) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *WgPeerMetrics) GetPersistentKeepalive() int64 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

type BirdProtocolStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Proto         string                 `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"` // e.g. "BGP", "Kernel", "Device"
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // e.g. "up", "down", "start"
	Info          string                 `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`   // e.g. "Established", "Connect", "Passive"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BirdProtocolStatus) Reset() {
	*x = BirdProtocolStatus{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BirdProtocolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdProtocolStatus) ProtoMessage() {}

func (x *BirdProtocolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdProtocolStatus.ProtoReflect.Descriptor instead.
func (*BirdProtocolStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *BirdProtocolStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BirdProtocolStatus) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *BirdProtocolStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BirdProtocolStatus) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type CommandRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandRequest_ApplyConfig
	//	*CommandRequest_ManageIface
	//	*CommandRequest_ReloadBird
	//	*CommandRequest_ApplyNft
	//	*CommandRequest_LookingGlass
	//	*CommandRequest_ProbeSystem
	//	*CommandRequest_RestartService
	Command       isCommandRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetCommand() isCommandRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandRequest) GetApplyConfig() *ApplyConfigFile {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ApplyConfig); ok {
			return x.ApplyConfig
		}
	}
	return nil
}

func (x *CommandRequest) GetManageIface() *ManageInterface {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ManageIface); ok {
			return x.ManageIface
		}
	}
	return nil
}

func (x *CommandRequest) GetReloadBird() *ReloadBirdCmd {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ReloadBird); ok {
			return x.ReloadBird
		}
	}
	return nil
}

func (x *CommandRequest) GetApplyNft() *ApplyNftablesCmd {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ApplyNft); ok {
			return x.ApplyNft
		}
	}
	return nil
}

func (x *CommandRequest) GetLookingGlass() *LookingGlassCmd {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_LookingGlass); ok {
			return x.LookingGlass
		}
	}
	return nil
}

func (x *CommandRequest) GetProbeSystem() *ProbeSystemCmd {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ProbeSystem); ok {
			return x.ProbeSystem
		}
	}
	return nil
}

func (x *CommandRequest) GetRestartService() *RestartServiceCmd {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_RestartService); ok {
			return x.RestartService
		}
	}
	return nil
}

type isCommandRequest_Command interface {
	isCommandRequest_Command()
}

type CommandRequest_ApplyConfig struct {
	ApplyConfig *ApplyConfigFile `protobuf:"bytes,10,opt,name=apply_config,json=applyConfig,proto3,oneof"`
}

type CommandRequest_ManageIface struct {
	ManageIface *ManageInterface `protobuf:"bytes,11,opt,name=manage_iface,json=manageIface,proto3,oneof"`
}

type CommandRequest_ReloadBird struct {
	ReloadBird *ReloadBirdCmd `protobuf:"bytes,12,opt,name=reload_bird,json=reloadBird,proto3,oneof"`
}

type CommandRequest_ApplyNft struct {
	ApplyNft *ApplyNftablesCmd `protobuf:"bytes,13,opt,name=apply_nft,json=applyNft,proto3,oneof"`
}

type CommandRequest_LookingGlass struct {
	LookingGlass *LookingGlassCmd `protobuf:"bytes,14,opt,name=looking_glass,json=lookingGlass,proto3,oneof"`
}

type CommandRequest_ProbeSystem struct {
	ProbeSystem *ProbeSystemCmd `protobuf:"bytes,15,opt,name=probe_system,json=probeSystem,proto3,oneof"`
}

type CommandRequest_RestartService struct {
	RestartService *RestartServiceCmd `protobuf:"bytes,16,opt,name=restart_service,json=restartService,proto3,oneof"`
}

func (*CommandRequest_ApplyConfig) isCommandRequest_Command() {}

func (*CommandRequest_ManageIface) isCommandRequest_Command() {}

func (*CommandRequest_ReloadBird) isCommandRequest_Command() {}

func (*CommandRequest_ApplyNft) isCommandRequest_Command() {}

func (*CommandRequest_LookingGlass) isCommandRequest_Command() {}

func (*CommandRequest_ProbeSystem) isCommandRequest_Command() {}

func (*CommandRequest_RestartService) isCommandRequest_Command() {}

type ApplyConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                               // Destination path (e.g. /etc/wireguard/wg42peer.conf)
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                         // File content
	FileMode      uint32                 `protobuf:"varint,3,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`      // e.g. 0600 or 0644
	Sha256Hash    string                 `protobuf:"bytes,4,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"` // Expected SHA-256 for verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigFile) Reset() {
	*x = ApplyConfigFile{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigFile) ProtoMessage() {}

func (x *ApplyConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigFile.ProtoReflect.Descriptor instead.
func (*ApplyConfigFile) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyConfigFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApplyConfigFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ApplyConfigFile) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *ApplyConfigFile) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

type ManageInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Action        ManageInterface_Action `protobuf:"varint,2,opt,name=action,proto3,enum=easy42.agent.v1.ManageInterface_Action" json:"action,omitempty"`
	ConfigFile    string                 `protobuf:"bytes,3,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"` // Optional path to wg config for SYNC_WG
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageInterface) Reset() {
	*x = ManageInterface{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageInterface) ProtoMessage() {}

func (x *ManageInterface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageInterface.ProtoReflect.Descriptor instead.
func (*ManageInterface) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ManageInterface) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *ManageInterface) GetAction() ManageInterface_Action {
	if x != nil {
		return x.Action
	}
	return ManageInterface_UP
}

func (x *ManageInterface) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

type ReloadBirdCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckOnly     bool                   `protobuf:"varint,1,opt,name=check_only,json=checkOnly,proto3" json:"check_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadBirdCmd) Reset() {
	*x = ReloadBirdCmd{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadBirdCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadBirdCmd) ProtoMessage() {}

func (x *ReloadBirdCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadBirdCmd.ProtoReflect.Descriptor instead.
func (*ReloadBirdCmd) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReloadBirdCmd) GetCheckOnly() bool {
	if x != nil {
		return x.CheckOnly
	}
	return false
}

type ApplyNftablesCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptPath    string                 `protobuf:"bytes,1,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyNftablesCmd) Reset() {
	*x = ApplyNftablesCmd{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNftablesCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNftablesCmd) ProtoMessage() {}

func (x *ApplyNftablesCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNftablesCmd.ProtoReflect.Descriptor instead.
func (*ApplyNftablesCmd) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyNftablesCmd) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

type LookingGlassCmd struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tool           LookingGlassCmd_Tool   `protobuf:"varint,1,opt,name=tool,proto3,enum=easy42.agent.v1.LookingGlassCmd_Tool" json:"tool,omitempty"`
	Target         string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Command        string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LookingGlassCmd) Reset() {
	*x = LookingGlassCmd{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookingGlassCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookingGlassCmd) ProtoMessage() {}

func (x *LookingGlassCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookingGlassCmd.ProtoReflect.Descriptor instead.
func (*LookingGlassCmd) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *LookingGlassCmd) GetTool() LookingGlassCmd_Tool {
	if x != nil {
		return x.Tool
	}
	return LookingGlassCmd_PING
}

func (x *LookingGlassCmd) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LookingGlassCmd) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *LookingGlassCmd) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *LookingGlassCmd) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ProbeSystemCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeSystemCmd) Reset() {
	*x = ProbeSystemCmd{}
	mi := &file_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSystemCmd) ProtoMessage() {}

func (x *ProbeSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSystemCmd.ProtoReflect.Descriptor instead.
func (*ProbeSystemCmd) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{17}
}

type RestartServiceCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // "wireguard", "bird"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServiceCmd) Reset() {
	*x = RestartServiceCmd{}
	mi := &file_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServiceCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServiceCmd) ProtoMessage() {}

func (x *RestartServiceCmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServiceCmd.ProtoReflect.Descriptor instead.
func (*RestartServiceCmd) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *RestartServiceCmd) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    uint64                 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *CommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Interfaces    []*InterfaceMetrics    `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ProbeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProbeResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ProbeResponse) GetInterfaces() []*InterfaceMetrics {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x0feasy42.agent.v1\"\xea\x04\n" +
	"\fAgentMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12E\n" +
	"\fregister_req\x18\n" +
	" \x01(\v2 .easy42.agent.v1.RegisterRequestH\x00R\vregisterReq\x12:\n" +
	"\theartbeat\x18\v \x01(\v2\x1a.easy42.agent.v1.HeartbeatH\x00R\theartbeat\x12@\n" +
	"\ttelemetry\x18\f \x01(\v2 .easy42.agent.v1.TelemetryReportH\x00R\ttelemetry\x12E\n" +
	"\fcommand_resp\x18\r \x01(\v2 .easy42.agent.v1.CommandResponseH\x00R\vcommandResp\x12?\n" +
	"\n" +
	"probe_resp\x18\x0e \x01(\v2\x1e.easy42.agent.v1.ProbeResponseH\x00R\tprobeResp\x12H\n" +
	"\rregister_resp\x18\x14 \x01(\v2!.easy42.agent.v1.RegisterResponseH\x00R\fregisterResp\x12D\n" +
	"\rheartbeat_ack\x18\x15 \x01(\v2\x1d.easy42.agent.v1.HeartbeatAckH\x00R\fheartbeatAck\x12B\n" +
	"\vcommand_req\x18\x16 \x01(\v2\x1f.easy42.agent.v1.CommandRequestH\x00R\n" +
	"commandReqB\t\n" +
	"\apayload\"\x88\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x17\n" +
	"\aos_info\x18\x03 \x01(\tR\x06osInfo\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\x89\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x126\n" +
	"\x17telemetry_interval_secs\x18\x03 \x01(\rR\x15telemetryIntervalSecs\",\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"/\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"\xc7\x02\n" +
	"\x0fTelemetryReport\x126\n" +
	"\x06system\x18\x01 \x01(\v2\x1e.easy42.agent.v1.SystemMetricsR\x06system\x12A\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\v2!.easy42.agent.v1.InterfaceMetricsR\n" +
	"interfaces\x129\n" +
	"\bwg_peers\x18\x03 \x03(\v2\x1e.easy42.agent.v1.WgPeerMetricsR\awgPeers\x12J\n" +
	"\x0ebird_protocols\x18\x04 \x03(\v2#.easy42.agent.v1.BirdProtocolStatusR\rbirdProtocols\x122\n" +
	"\x05disks\x18\x05 \x03(\v2\x1c.easy42.agent.v1.DiskMetricsR\x05disks\"\x80\x01\n" +
	"\vDiskMetrics\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x04 \x01(\x04R\tfreeBytes\"\xcc\x01\n" +
	"\rSystemMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x04R\x10memoryTotalBytes\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x04R\ruptimeSeconds\x12\x19\n" +
	"\bload_avg\x18\x05 \x03(\x02R\aloadAvg\"\x87\x02\n" +
	"\x10InterfaceMetrics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x13\n" +
	"\x05is_up\x18\x02 \x01(\bR\x04isUp\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x04R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x05 \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x06 \x01(\x04R\ttxPackets\x12\x1b\n" +
	"\trx_errors\x18\a \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\b \x01(\x04R\btxErrors\x12\x1c\n" +
	"\taddresses\x18\t \x03(\tR\taddresses\"\x8a\x02\n" +
	"\rWgPeerMetrics\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12.\n" +
	"\x13last_handshake_time\x18\x04 \x01(\x03R\x11lastHandshakeTime\x12\x19\n" +
	"\brx_bytes\x18\x05 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x06 \x01(\x04R\atxBytes\x121\n" +
	"\x14persistent_keepalive\x18\a \x01(\x03R\x13persistentKeepalive\"h\n" +
	"\x12BirdProtocolStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05proto\x18\x02 \x01(\tR\x05proto\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x12\n" +
	"\x04info\x18\x04 \x01(\tR\x04info\"\xab\x04\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12E\n" +
	"\fapply_config\x18\n" +
	" \x01(\v2 .easy42.agent.v1.ApplyConfigFileH\x00R\vapplyConfig\x12E\n" +
	"\fmanage_iface\x18\v \x01(\v2 .easy42.agent.v1.ManageInterfaceH\x00R\vmanageIface\x12A\n" +
	"\vreload_bird\x18\f \x01(\v2\x1e.easy42.agent.v1.ReloadBirdCmdH\x00R\n" +
	"reloadBird\x12@\n" +
	"\tapply_nft\x18\r \x01(\v2!.easy42.agent.v1.ApplyNftablesCmdH\x00R\bapplyNft\x12G\n" +
	"\rlooking_glass\x18\x0e \x01(\v2 .easy42.agent.v1.LookingGlassCmdH\x00R\flookingGlass\x12D\n" +
	"\fprobe_system\x18\x0f \x01(\v2\x1f.easy42.agent.v1.ProbeSystemCmdH\x00R\vprobeSystem\x12M\n" +
	"\x0frestart_service\x18\x10 \x01(\v2\".easy42.agent.v1.RestartServiceCmdH\x00R\x0erestartServiceB\t\n" +
	"\acommand\"}\n" +
	"\x0fApplyConfigFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\tfile_mode\x18\x03 \x01(\rR\bfileMode\x12\x1f\n" +
	"\vsha256_hash\x18\x04 \x01(\tR\n" +
	"sha256Hash\"\xdc\x01\n" +
	"\x0fManageInterface\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12?\n" +
	"\x06action\x18\x02 \x01(\x0e2'.easy42.agent.v1.ManageInterface.ActionR\x06action\x12\x1f\n" +
	"\vconfig_file\x18\x03 \x01(\tR\n" +
	"configFile\"@\n" +
	"\x06Action\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\v\n" +
	"\aRESTART\x10\x02\x12\v\n" +
	"\aSYNC_WG\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04\".\n" +
	"\rReloadBirdCmd\x12\x1d\n" +
	"\n" +
	"check_only\x18\x01 \x01(\bR\tcheckOnly\"3\n" +
	"\x10ApplyNftablesCmd\x12\x1f\n" +
	"\vscript_path\x18\x01 \x01(\tR\n" +
	"scriptPath\"\xf4\x01\n" +
	"\x0fLookingGlassCmd\x129\n" +
	"\x04tool\x18\x01 \x01(\x0e2%.easy42.agent.v1.LookingGlassCmd.ToolR\x04tool\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\"7\n" +
	"\x04Tool\x12\b\n" +
	"\x04PING\x10\x00\x12\x0e\n" +
	"\n" +
	"TRACEROUTE\x10\x01\x12\t\n" +
	"\x05BIRDC\x10\x02\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x03\"\x10\n" +
	"\x0eProbeSystemCmd\"6\n" +
	"\x11RestartServiceCmd\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xb8\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x04R\n" +
	"durationMs\"\x8d\x01\n" +
	"\rProbeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12A\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2!.easy42.agent.v1.InterfaceMetricsR\n" +
	"interfacesB%Z#easy42/internal/agent/proto;agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_agent_proto_goTypes = []any{
	(ManageInterface_Action)(0), // 0: easy42.agent.v1.ManageInterface.Action
	(LookingGlassCmd_Tool)(0),   // 1: easy42.agent.v1.LookingGlassCmd.Tool
	(*AgentMessage)(nil),        // 2: easy42.agent.v1.AgentMessage
	(*RegisterRequest)(nil),     // 3: easy42.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 4: easy42.agent.v1.RegisterResponse
	(*Heartbeat)(nil),           // 5: easy42.agent.v1.Heartbeat
	(*HeartbeatAck)(nil),        // 6: easy42.agent.v1.HeartbeatAck
	(*TelemetryReport)(nil),     // 7: easy42.agent.v1.TelemetryReport
	(*DiskMetrics)(nil),         // 8: easy42.agent.v1.DiskMetrics
	(*SystemMetrics)(nil),       // 9: easy42.agent.v1.SystemMetrics
	(*InterfaceMetrics)(nil),    // 10: easy42.agent.v1.InterfaceMetrics
	(*WgPeerMetrics)(nil),       // 11: easy42.agent.v1.WgPeerMetrics
	(*BirdProtocolStatus)(nil),  // 12: easy42.agent.v1.BirdProtocolStatus
	(*CommandRequest)(nil),      // 13: easy42.agent.v1.CommandRequest
	(*ApplyConfigFile)(nil),     // 14: easy42.agent.v1.ApplyConfigFile
	(*ManageInterface)(nil),     // 15: easy42.agent.v1.ManageInterface
	(*ReloadBirdCmd)(nil),       // 16: easy42.agent.v1.ReloadBirdCmd
	(*ApplyNftablesCmd)(nil),    // 17: easy42.agent.v1.ApplyNftablesCmd
	(*LookingGlassCmd)(nil),     // 18: easy42.agent.v1.LookingGlassCmd
	(*ProbeSystemCmd)(nil),      // 19: easy42.agent.v1.ProbeSystemCmd
	(*RestartServiceCmd)(nil),   // 20: easy42.agent.v1.RestartServiceCmd
	(*CommandResponse)(nil),     // 21: easy42.agent.v1.CommandResponse
	(*ProbeResponse)(nil),       // 22: easy42.agent.v1.ProbeResponse
}
var file_proto_agent_proto_depIdxs = []int32{
	3,  // 0: easy42.agent.v1.AgentMessage.register_req:type_name -> easy42.agent.v1.RegisterRequest
	5,  // 1: easy42.agent.v1.AgentMessage.heartbeat:type_name -> easy42.agent.v1.Heartbeat
	7,  // 2: easy42.agent.v1.AgentMessage.telemetry:type_name -> easy42.agent.v1.TelemetryReport
	21, // 3: easy42.agent.v1.AgentMessage.command_resp:type_name -> easy42.agent.v1.CommandResponse
	22, // 4: easy42.agent.v1.AgentMessage.probe_resp:type_name -> easy42.agent.v1.ProbeResponse
	4,  // 5: easy42.agent.v1.AgentMessage.register_resp:type_name -> easy42.agent.v1.RegisterResponse
	6,  // 6: easy42.agent.v1.AgentMessage.heartbeat_ack:type_name -> easy42.agent.v1.HeartbeatAck
	13, // 7: easy42.agent.v1.AgentMessage.command_req:type_name -> easy42.agent.v1.CommandRequest
	9,  // 8: easy42.agent.v1.TelemetryReport.system:type_name -> easy42.agent.v1.SystemMetrics
	10, // 9: easy42.agent.v1.TelemetryReport.interfaces:type_name -> easy42.agent.v1.InterfaceMetrics
	11, // 10: easy42.agent.v1.TelemetryReport.wg_peers:type_name -> easy42.agent.v1.WgPeerMetrics
	12, // 11: easy42.agent.v1.TelemetryReport.bird_protocols:type_name -> easy42.agent.v1.BirdProtocolStatus
	8,  // 12: easy42.agent.v1.TelemetryReport.disks:type_name -> easy42.agent.v1.DiskMetrics
	14, // 13: easy42.agent.v1.CommandRequest.apply_config:type_name -> easy42.agent.v1.ApplyConfigFile
	15, // 14: easy42.agent.v1.CommandRequest.manage_iface:type_name -> easy42.agent.v1.ManageInterface
	16, // 15: easy42.agent.v1.CommandRequest.reload_bird:type_name -> easy42.agent.v1.ReloadBirdCmd
	17, // 16: easy42.agent.v1.CommandRequest.apply_nft:type_name -> easy42.agent.v1.ApplyNftablesCmd
	18, // 17: easy42.agent.v1.CommandRequest.looking_glass:type_name -> easy42.agent.v1.LookingGlassCmd
	19, // 18: easy42.agent.v1.CommandRequest.probe_system:type_name -> easy42.agent.v1.ProbeSystemCmd
	20, // 19: easy42.agent.v1.CommandRequest.restart_service:type_name -> easy42.agent.v1.RestartServiceCmd
	0,  // 20: easy42.agent.v1.ManageInterface.action:type_name -> easy42.agent.v1.ManageInterface.Action
	1,  // 21: easy42.agent.v1.LookingGlassCmd.tool:type_name -> easy42.agent.v1.LookingGlassCmd.Tool
	10, // 22: easy42.agent.v1.ProbeResponse.interfaces:type_name -> easy42.agent.v1.InterfaceMetrics
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_RegisterReq)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Telemetry)(nil),
		(*AgentMessage_CommandResp)(nil),
		(*AgentMessage_ProbeResp)(nil),
		(*AgentMessage_RegisterResp)(nil),
		(*AgentMessage_HeartbeatAck)(nil),
		(*AgentMessage_CommandReq)(nil),
	}
	file_proto_agent_proto_msgTypes[11].OneofWrappers = []any{
		(*CommandRequest_ApplyConfig)(nil),
		(*CommandRequest_ManageIface)(nil),
		(*CommandRequest_ReloadBird)(nil),
		(*CommandRequest_ApplyNft)(nil),
		(*CommandRequest_LookingGlass)(nil),
		(*CommandRequest_ProbeSystem)(nil),
		(*CommandRequest_RestartService)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
