mod client;
mod collector;
mod config;
mod executor;

use std::path::PathBuf;
use clap::Parser;
use tracing::info;
use tracing_subscriber::EnvFilter;

use crate::client::AgentClient;
use crate::config::AgentConfig;

#[derive(Parser, Debug)]
#[command(name = "easy42-agent", version = "0.1.0", about = "Easy42 Node Agent")]
struct Cli {
    /// Path to configuration file
    #[arg(short, long, default_value = "/etc/easy42/agent.toml")]
    config: PathBuf,

    /// Easy42 controller server URL (e.g. https://controller.easy42.net)
    #[arg(short, long)]
    server: Option<String>,

    /// Authentication token generated by Easy42 server
    #[arg(short, long)]
    token: Option<String>,

    /// Override node name
    #[arg(short, long)]
    node_name: Option<String>,

    /// Telemetry reporting interval in seconds
    #[arg(short, long)]
    interval: Option<u64>,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Install ring as default CryptoProvider for rustls
    let _ = rustls::crypto::ring::default_provider().install_default();

    let cli = Cli::parse();

    // 1. Try to load config file or construct from CLI flags
    let mut config = if cli.config.exists() {
        match AgentConfig::load_from_file(&cli.config) {
            Ok(c) => c,
            Err(e) => {
                eprintln!("Failed to load config file {:?}: {}", cli.config, e);
                std::process::exit(1);
            }
        }
    } else if let (Some(server), Some(token)) = (cli.server.clone(), cli.token.clone()) {
        AgentConfig {
            server,
            token,
            log_level: "info".to_string(),
            telemetry_interval_secs: 10,
            node_name: None,
        }
    } else {
        eprintln!(
            "Configuration file {:?} does not exist and --server / --token were not provided.\n\
            Run with --help for options.",
            cli.config
        );
        std::process::exit(1);
    };

    // Override with CLI flags if provided
    if let Some(srv) = cli.server {
        config.server = srv;
    }
    if let Some(tok) = cli.token {
        config.token = tok;
    }
    if let Some(name) = cli.node_name {
        config.node_name = Some(name);
    }
    if let Some(inv) = cli.interval {
        config.telemetry_interval_secs = inv;
    }

    // 2. Initialize tracing
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new(&config.log_level));
    tracing_subscriber::fmt().with_env_filter(filter).init();

    info!("Starting Easy42 Agent v0.1.0");
    info!("Target server: {}", config.server);

    let client = AgentClient::new(config);

    // 3. Run client with signal handling
    tokio::select! {
        _ = client.run() => {},
        _ = tokio::signal::ctrl_c() => {
            info!("Received shutdown signal, exiting...");
        }
    }

    Ok(())
}
